# Generated by Django 3.2.7 on 2021-11-17 22:59

import authentication.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=15, validators=[authentication.validators.validate_special_char])),
                ('last_name', models.CharField(max_length=15, validators=[authentication.validators.validate_special_char])),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('single', 'Single'), ('dating', 'Dating'), ('married', 'Married')], default='single', max_length=20)),
                ('confirmed_phoneno', models.BooleanField(default=False)),
                ('confirmed_id', models.BooleanField(default=False)),
                ('confirmed_address', models.BooleanField(default=False)),
                ('confirmed_email', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numbers', models.CharField(max_length=300)),
                ('verified', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='First_Partner', to=settings.AUTH_USER_MODEL)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Second_Partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.CharField(blank=True, help_text='Enter a correct phone number', max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Your phone number is not in the right format', regex='^\\+(?:[0-9] ?){6,14}[0-9]$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
